# Generated by Django 5.1 on 2024-08-21 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('authorized', models.BooleanField(default=False)),
                ('authorized_at', models.DateField(blank=True, default=None, null=True)),
                ('risk', models.CharField(max_length=1)),
            ],
        ),
    ]
